apiVersion: apps/v1
kind: Deployment
metadata:
  name: rancher-desktop-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rancher-desktop-demo
  template:
    metadata:
      labels:
        app: rancher-desktop-demo
    spec:
      containers:
      - name: rancher-desktop-demo
        image: dvdemo:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "512Mi"
            cpu: "0.5"
          limits:
            memory: "512Mi"
            cpu: "0.5"
---
apiVersion: v1
kind: Service
metadata:
  name: rancher-desktop-demo
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: rancher-desktop-demo
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rancher-desktop-demo
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: rancher-desktop-demo
            port:
              number: 80
